# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
