# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_auto_20171020_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheel',
            old_name='sname',
            new_name='name',
        ),
    ]
