# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=64, unique=True)),
                ('grade_date', models.DateTimeField()),
                ('grade_girl_num', models.IntegerField()),
                ('grade_boy_num', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('student_age', models.IntegerField(db_column='age')),
                ('student_gender', models.BooleanField(default=True)),
                ('student_contend', models.CharField(max_length=64)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('student_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Grade')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'student',
            },
        ),
    ]
