# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bianju',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=128, verbose_name='姓名')),
                ('pxingbie', models.BooleanField(default=True, verbose_name='性别')),
                ('pchusheng', models.DateTimeField(auto_now_add=True, verbose_name='出生日期')),
                ('pchushengdi', models.CharField(max_length=64, verbose_name='出生地')),
                ('pjianjie', models.TextField(verbose_name='简介')),
                ('purl', models.CharField(max_length=512, verbose_name='肖像')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Daoyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=128, verbose_name='姓名')),
                ('pxingbie', models.BooleanField(default=True, verbose_name='性别')),
                ('pchusheng', models.DateTimeField(auto_now_add=True, verbose_name='出生日期')),
                ('pchushengdi', models.CharField(max_length=64, verbose_name='出生地')),
                ('pjianjie', models.TextField(verbose_name='简介')),
                ('purl', models.CharField(max_length=512, verbose_name='肖像')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diqu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dqname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Guojia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gjname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Leixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lxname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=128)),
                ('shangying', models.DateField(auto_now_add=True)),
                ('pianchang', models.IntegerField(default=90)),
                ('youming', models.CharField(max_length=128)),
                ('jianjie', models.TextField()),
                ('url', models.CharField(max_length=512, verbose_name='封面')),
                ('is_ban', models.BooleanField(default=False)),
                ('diqu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Diqu')),
                ('guojia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Guojia')),
            ],
            options={
                'ordering': ['shangying'],
            },
        ),
        migrations.CreateModel(
            name='Yanyuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=128, verbose_name='姓名')),
                ('pxingbie', models.BooleanField(default=True, verbose_name='性别')),
                ('pchusheng', models.DateTimeField(auto_now_add=True, verbose_name='出生日期')),
                ('pchushengdi', models.CharField(max_length=64, verbose_name='出生地')),
                ('pjianjie', models.TextField(verbose_name='简介')),
                ('purl', models.CharField(max_length=512, verbose_name='肖像')),
                ('movie', models.ManyToManyField(to='movie.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Yuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='yuyan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Yuyan'),
        ),
        migrations.AddField(
            model_name='leixing',
            name='movie',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='daoyan',
            name='movie',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='bianju',
            name='movie',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
    ]
